**LOADING** **DATA**

In [ ]:
!pip install kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /usr/local/lib/python3.12/dist-packages (from kagglehub) (0.1.18)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (5.29.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2026.2.25)

In [ ]:
import kagglehub
path = kagglehub.dataset_download("tmdb/tmdb-movie-metadata")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'tmdb-movie-metadata' dataset.
Path to dataset files: /kaggle/input/tmdb-movie-metadata

In [ ]:
import kagglehub

paths = kagglehub.dataset_download("grouplens/movielens-20m-dataset")

print("Path to dataset files:", paths)

Downloading to /root/.cache/kagglehub/datasets/grouplens/movielens-20m-dataset/1.archive...

100%|██████████| 195M/195M [00:01<00:00, 121MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/grouplens/movielens-20m-dataset/versions/1

In [ ]:
import os
os.listdir(path)

['tmdb_5000_movies.csv', 'tmdb_5000_credits.csv']

In [ ]:
print(os.listdir(paths))

['genome_scores.csv', 'link.csv', 'movie.csv', 'tag.csv', 'rating.csv', 'genome_tags.csv']

In [ ]:
import pandas as pd
import os
import warnings
warnings.filterwarnings('ignore')
movies_tmdb = pd.read_csv(path + "/tmdb_5000_movies.csv")
credits = pd.read_csv(path + "/tmdb_5000_credits.csv")


ratings = pd.read_csv(os.path.join(paths, "rating.csv"))
movies_movielens = pd.read_csv(os.path.join(paths, "movie.csv"))
links   = pd.read_csv(os.path.join(paths, "link.csv"))

# **preprocessing**

In [ ]:
print(ratings.shape)
print(movies_movielens.shape)
print(links.shape)
print(movies_tmdb.shape)

(20000263, 4)
(27278, 3)
(27278, 3)
(4803, 20)

In [ ]:
ratings.head()

   userId  movieId  rating            timestamp
0       1        2     3.5  2005-04-02 23:53:47
1       1       29     3.5  2005-04-02 23:31:16
2       1       32     3.5  2005-04-02 23:33:39
3       1       47     3.5  2005-04-02 23:32:07
4       1       50     3.5  2005-04-02 23:29:40

In [ ]:
movies_movielens.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [ ]:
movies_tmdb.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
movies_tmdb[['id','title','overview']].head()

,id,title,overview
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [ ]:
print(ratings.isnull().sum())

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [ ]:
print(ratings.duplicated().sum())

0

In [ ]:
print(movies_movielens.isnull().sum())

movieId    0
title      0
genres     0
dtype: int64

In [ ]:
movies_movielens.duplicated().sum()

np.int64(0)

In [ ]:
movies_movielens['genres'] = movies_movielens['genres'].str.split('|')

In [ ]:
movies_movielens.head()

,movieId,title,genres
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]"
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]"
2,3,Grumpier Old Men (1995),"[Comedy, Romance]"
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]"
4,5,Father of the Bride Part II (1995),[Comedy]

In [ ]:
movies_tmdb.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [ ]:
tmdb_selected = movies_tmdb[['id', 'title', 'overview', 'keywords',
                       'vote_average', 'vote_count', 'popularity',
                       'release_date', 'runtime', 'original_language']]

In [ ]:
import ast

def extract_names(text):
    try:
        items = ast.literal_eval(text)
        return [item['name'] for item in items]
    except:
        return []

tmdb_selected['keywords'] = tmdb_selected['keywords'].apply(extract_names)
print(tmdb_selected['keywords'].head())

0    [culture clash, future, space war, space colon...
1    [ocean, drug abuse, exotic island, east india ...
2    [spy, based on novel, secret agent, sequel, mi...
3    [dc comics, crime fighter, terrorist, secret i...
4    [based on novel, mars, medallion, space travel...
Name: keywords, dtype: object

In [ ]:
tmdb_selected['runtime'] = tmdb_selected['runtime'].fillna(tmdb_selected['runtime'].median())
tmdb_selected['release_date'] = pd.to_datetime(tmdb_selected['release_date'])
tmdb_selected['release_year'] = tmdb_selected['release_date'].dt.year
tmdb_selected['release_month'] = tmdb_selected['release_date'].dt.month
tmdb_selected = tmdb_selected.dropna(subset=['release_date'])
tmdb_selected = tmdb_selected.drop(columns=['release_date'])

In [ ]:
movies_tmdb.duplicated().sum()

np.int64(0)

In [ ]:
tmdb_selected = tmdb_selected.dropna(subset=['overview'])
tmdb_selected['overview'] =tmdb_selected['overview'].str.strip()

In [ ]:
tmdb_selected.head()

,id,title,overview,keywords,vote_average,vote_count,popularity,runtime,original_language,release_year,release_month
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...",7.2,11800,150.437577,162.0,en,2009.0,12.0
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...",6.9,4500,139.082615,169.0,en,2007.0,5.0
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...",6.3,4466,107.376788,148.0,en,2015.0,10.0
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...",7.6,9106,112.312950,165.0,en,2012.0,7.0
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...",6.1,2124,43.926995,132.0,en,2012.0,3.0

In [ ]:
links['tmdbId'] = links['tmdbId'].dropna().astype(int)
tmdb_selected['id'] = tmdb_selected['id'].astype(int)

In [ ]:
merged = links.merge(tmdb_selected,
                     left_on='tmdbId',
                     right_on='id')

In [ ]:
merged = merged.merge(movies_movielens[['movieId','genres']], on='movieId')

In [ ]:
print(merged.shape)

(4227, 15)

In [ ]:
print(merged.head())

   movieId  imdbId   tmdbId     id                   title  \
0        1  114709    862.0    862               Toy Story
1       10  113189    710.0    710               GoldenEye
2       11  112346   9087.0   9087  The American President
3       14  113987  10858.0  10858                   Nixon
4       15  112760   1408.0   1408        Cutthroat Island

                                            overview  \
0  Led by Woody, Andy's toys live happily in his ...
1  James Bond must unmask the mysterious head of ...
2  Widowed U.S. president Andrew Shepherd, one of...
3  An all-star cast powers this epic look at Amer...
4  Morgan Adams and her slave, William Shaw, are ...

                                            keywords  vote_average  \
0  [jealousy, toy, boy, friendship, friends, riva...           7.7
1  [cuba, falsely accused, secret identity, compu...           6.6
2  [white house, usa president, new love, widower...           6.5
3  [usa president, presidential election, waterga...           7.1
4  [exotic island, treasure, map, ship, scalp, pi...           5.7

   vote_count  popularity  runtime original_language  release_year  \
0        5269   73.640445     81.0                en        1995.0
1        1174   59.824565    130.0                en        1995.0
2         195   11.056763    106.0                en        1995.0
3          71    3.770161    192.0                en        1995.0
4         136    7.029308    119.0                en        1995.0

   release_month                                             genres
0           10.0  [Adventure, Animation, Children, Comedy, Fantasy]
1           11.0                      [Action, Adventure, Thriller]
2           11.0                           [Comedy, Drama, Romance]
3           12.0                                            [Drama]
4           12.0                       [Action, Adventure, Romance]

In [ ]:
merged.isnull().sum()

movieId              0
imdbId               0
tmdbId               0
id                   0
title                0
overview             0
keywords             0
vote_average         0
vote_count           0
popularity           0
runtime              0
original_language    0
release_year         0
release_month        0
genres               0
dtype: int64

In [ ]:
merged = merged.drop_duplicates(subset='movieId')

In [ ]:
merged = merged.drop(columns=['id', 'imdbId'])

In [ ]:
merged.head()

,movieId,tmdbId,title,overview,keywords,vote_average,vote_count,popularity,runtime,original_language,release_year,release_month,genres
0,1,862.0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[jealousy, toy, boy, friendship, friends, riva...",7.7,5269,73.640445,81.0,en,1995.0,10.0,"[Adventure, Animation, Children, Comedy, Fantasy]"
1,10,710.0,GoldenEye,James Bond must unmask the mysterious head of ...,"[cuba, falsely accused, secret identity, compu...",6.6,1174,59.824565,130.0,en,1995.0,11.0,"[Action, Adventure, Thriller]"
2,11,9087.0,The American President,"Widowed U.S. president Andrew Shepherd, one of...","[white house, usa president, new love, widower...",6.5,195,11.056763,106.0,en,1995.0,11.0,"[Comedy, Drama, Romance]"
3,14,10858.0,Nixon,An all-star cast powers this epic look at Amer...,"[usa president, presidential election, waterga...",7.1,71,3.770161,192.0,en,1995.0,12.0,[Drama]
4,15,1408.0,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...","[exotic island, treasure, map, ship, scalp, pi...",5.7,136,7.029308,119.0,en,1995.0,12.0,"[Action, Adventure, Romance]"

In [ ]:

valid_movies = merged['movieId'].unique()
ratings_filtered = ratings[ratings['movieId'].isin(valid_movies)]

In [ ]:
ratings_filtered = ratings_filtered.drop(columns=['timestamp'])

In [ ]:
ratings_filtered.head()

   userId  movieId  rating
3       1       47     3.5
4       1       50     3.5
5       1      112     3.5
6       1      151     4.0
7       1      223     4.0

In [ ]:
print(ratings_filtered.shape)

(13425642, 3)

**user watch history**

In [ ]:
transactions = ratings_filtered.groupby('userId')['movieId'].apply(list).reset_index()
transactions.columns = ['userId', 'movies']

print(transactions.head())

   userId                                             movies
0       1  [47, 50, 112, 151, 223, 253, 260, 296, 318, 33...
1       2  [62, 70, 110, 260, 266, 480, 541, 589, 891, 92...
2       3  [1, 50, 160, 175, 196, 223, 260, 318, 329, 337...
3       4  [10, 19, 165, 329, 350, 356, 367, 370, 377, 38...
4       5  [11, 17, 60, 62, 104, 110, 140, 150, 224, 235,...

In [ ]:

movie_dict = merged.set_index('movieId')['title'].to_dict()


transactions['movies'] = transactions['movies'].apply(
    lambda x: [movie_dict.get(m, str(m)) for m in x]
)

print(transactions.head())

   userId                                             movies
0       1  [Se7en, The Usual Suspects, Rumble in the Bron...
1       2  [Mr. Holland's Opus, From Dusk Till Dawn, Brav...
2       3  [Toy Story, The Usual Suspects, Congo, Kids, S...
3       4  [GoldenEye, Ace Ventura: When Nature Calls, Di...
4       5  [The American President, Sense and Sensibility...

# **df for visualization extra**

In [ ]:
df = movies_tmdb

In [ ]:
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [ ]:
df.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [ ]:
df.drop([
    'homepage',
    'tagline',
    'original_title',
    'overview',
    'keywords',
    'genres'
], axis=1, inplace=True)

In [ ]:
df['production_companies'] = df['production_companies'].apply(extract_names)
df['production_countries'] = df['production_countries'].apply(extract_names)
df['spoken_languages'] = df['spoken_languages'].apply(extract_names)

In [ ]:
df['runtime'] = df['runtime'].fillna(df['runtime'].median())
df = df.dropna(subset=['release_date'])

In [ ]:
df.isnull().sum()

budget                  0
id                      0
original_language       0
popularity              0
production_companies    0
production_countries    0
release_date            0
revenue                 0
runtime                 0
spoken_languages        0
status                  0
title                   0
vote_average            0
vote_count              0
dtype: int64

In [ ]:
df.head()

,budget,id,original_language,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,title,vote_average,vote_count
0,237000000,19995,en,150.437577,"[Ingenious Film Partners, Twentieth Century Fo...","[United States of America, United Kingdom]",2009-12-10,2787965087,162.0,"[English, Español]",Released,Avatar,7.2,11800
1,300000000,285,en,139.082615,"[Walt Disney Pictures, Jerry Bruckheimer Films...",[United States of America],2007-05-19,961000000,169.0,[English],Released,Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,206647,en,107.376788,"[Columbia Pictures, Danjaq, B24]","[United Kingdom, United States of America]",2015-10-26,880674609,148.0,"[Français, English, Español, Italiano, Deutsch]",Released,Spectre,6.3,4466
3,250000000,49026,en,112.312950,"[Legendary Pictures, Warner Bros., DC Entertai...",[United States of America],2012-07-16,1084939099,165.0,[English],Released,The Dark Knight Rises,7.6,9106
4,260000000,49529,en,43.926995,[Walt Disney Pictures],[United States of America],2012-03-07,284139100,132.0,[English],Released,John Carter,6.1,2124

In [ ]:
df['release_date'] = pd.to_datetime(df['release_date'])
df['year'] = df['release_date'].dt.year
df['month'] = df['release_date'].dt.month

In [ ]:
df = df[df['budget'] > 0]
df = df[df['revenue'] > 0]
df = df[df['runtime'] > 0]
df['profit'] = df['revenue'] - df['budget']
df['roi'] = df['revenue'] / df['budget']
df['roi'] = df['roi'].replace([float('inf'), -float('inf')], 0)